### ISSUE TITLE
Move source into separate /lecture-hoarder directory

### ISSUE THREAD

**Issue by ed-cooper** [ed-cooper/lecture-hoarder#10]
The base directory for the repo has became polluted with various files

Is it time to move the source code into its own directory?

**Comment by csnewman** [comment]
That would seem a good course of action, or possibly a ```src``` directory instead. Exact path will make little difference with #9

**Comment by ed-cooper** [comment]
I have seen various places where `src` is discouraged as a generic name, where something more specific is preferred.

Having said that, my first thought was also to go with `src`

**Comment by ed-cooper** [comment]
Is it still worth it now that we only have one python file?

Official guidance is that single python files should stay in the home directory
