### ISSUE TITLE
Video page format change

### ISSUE THREAD

**Issue by csnewman** [ed-cooper/lecture-hoarder#15]
Dom of site has changed. Videos no longer download

**Comment by ed-cooper** [comment]
Video widget is now an iframe, however there is still a download button

Also a good opportunity to improve the error message for unexpeceted download statuses

The odd thing here is it that it appears that an exception is being raised but is silently caught. I guess it's a quirk of concurrences and I'll ignore it for now - in a roundabout way we'll still see an error message displayed

**Comment by ed-cooper** [comment]
Fixed
